version: "3"
services:
  server:
    image: opp
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/onlinepaymentprocess?serverTimezone=UTC&useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
    restart: on-failure

  mysqldb:
    image: mysql:8.0.22
    networks:
      - springmysql-net
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=colendi123
      - MYSQL_DATABASE=onlinepaymentprocess
      - MYSQL_USER=burcu
      - MYSQL_PASSWORD=colendi123

networks:
  springmysql-net: